when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            collect: false
            collect_parameter: 'profile' # Active le profiler seulement si ?profile=1 est présent
            collect_serializer_data: false

when@test:
    framework:
        profiler:
            collect: false
            collect_serializer_data: true
